locales:
  en:
    name: Lule Sami Keyboards
    description: >-
      Keyboards for Lule Sámi from the Divvun and Giellatekno groups at UiT.
      For Windows, macOS, Linux, ChromeOS, smartphones and tablets.
      Layouts for Norway and Sweden.
  nb:
    name: Lulesamiske tastatur
    description: >-
      Tastatur for lulesamisk fra Divvun-gruppa og Giellatekno-gruppene ved UiT.
      For Windows, macOS, Linux, ChromeOS, mobiltelefoner og nettbrett.
      Tilpasset for Norge og Sverige.
  nn:
    name: Lulesamiske tastatur
    description: >-
      Tastatur for lulesamisk frå Divvun- og Giellatekno-gruppene ved UiT.
      For Windows, macOS, Linux, ChromeOS, mobiltelefonar og nettbrett.
      Tilpassa for Noreg og Sverige.
  se:
    name: Julevsámi boallobeavddit
    description: >-
      Boallobeavddit julevsámegiela várás Divvun- ja Giellatekno-joavkkuin UiT:s.
      Doaibmá Windowsis, macOS:s, Linuxis, ChromeOS:s, mátketelefovnnain ja dihtordulbosiin.
      Heivehuvvon Norgii ja Ruŧŧii.
  sma:
    name: Åarjelsaemien båaloebuertie
    description: >-
      Åarjelsaemien båaloebuertie UiT:n Divvun jïh Giellatekon-dåehkijste daelie
      Windowsisnie, macOS:sne, Linuxisnie, ChromeOS:sne, mobiltelefovnide jïh
      nehtepreerjine jåhta. Nöörjese jïh Sveerjese sjïehtesjovveme.
  smj:
    name: Julevsáme boallobievde
    description: >-
      Julevsáme boallobievde UiT:a Divvun- ja Giellatekno-juohkusijs.
      Windowsij, macOS:aj, Linuxij, ChromeOS:aj, mobijlajda ja pettajda.
      Hiebaduvvam Vuodnaj ja Svierigij.
  sv:
    name: Lulesamiska tangentbord
    description: >-
      Tangentbord för lulesamiska från Divvun- och Giellatekno-grupperna ved UiT.
      För Windows, macOS, Linux, ChromeOS, mobiltelefoner och surfplattor.
      Anpassade för Norge och Sverige.
author: 'The Divvun and Giellatekno Groups, UiT Norgga árktalaš universitehta'
copyright: © 2024 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
