template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 11
template_sha = "9f221e6df0bb7d28b8bd1395a58e841138a56154"

[replacements]
__UND2C__ = "smj"
__UNDEFINED__ = "Lule Sami"
__UND__ = "smj"
