template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 16
template_sha = "b5f3d4e78b098720e79340d8f8022316bf37d1d3"

[replacements]
__UND2C__ = "smj"
__UNDEFINED__ = "Lule Sami"
__UND__ = "smj"
