template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 9
template_sha = "7bcdb785f696fdc6c38d9ff54678d1b7921aff48"

[replacements]
__UND2C__ = "smj"
__UNDEFINED__ = "Lule Sami"
__UND__ = "smj"
